version: "2.24.5"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    container_name: devnest_c
    ports:
      - '8000:6000'
    image: dev:nest
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
      # to create a named volume linking host OS to container OS
      # - ./node_modules:/app/node_modules
      # to create an anonymous volume without linking host OS to container OS (fixes bcrypt issue)
      - /app/node_modules 
  live:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: live
    container_name: livenest_c
    ports:
      - '8080:6000'
    image: live:nest
    environment:
      - NODE_ENV=live