version: "2.24.5"
services:
  nestapp_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: dev
    container_name: nestapp_dev_c
    ports:
      - '8000:9090'
    image: nestapp_dev:v1
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
      # to create a named volume linking host OS to container OS
      # - ./node_modules:/app/node_modules
      # to create an anonymous volume without linking host OS to container OS (fixes bcrypt issue)
      - /app/node_modules 
  nestapp_live:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: live
    container_name: nestapp_live_c
    ports:
      - '8080:9090'
    image: nestapp_live:v1
    environment:
      - NODE_ENV=live